# unix
mkdir -p build/debug;

cmake -G "Ninja" -B build/debug_linux -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=true -DBECC_BUILD_TOOLS=true -DBECC_BUILD_TESTS=true -DBECC_BUILD_VENDOR_STB=true -DBECC_BUILD_VENDOR_SDL3=true -DBECC_BUILD_VENDOR_HARU=true -DBECC_BUILD_VENDOR_NANOSVG=true -DBECC_BUILD_VENDOR_ZXING_CPP=true -DBECC_BUILD_VENDOR_COUCHBASE_CXX_CLIENT=true;

cmake --build build/debug --target all;