#ifndef BECC_CONFIG_HH
#define BECC_CONFIG_HH

#define BECC_VERSION_MAJOR @BECC_VERSION_MAJOR@

#define BECC_VERSION_MINOR @BECC_VERSION_MINOR@

#define BECC_VERSION_PATCH @BECC_VERSION_PATCH@

#define BECC_VERSION_RELEASE_DATE @BECC_VERSION_RELEASE_DATE@

#endif // BECC_CONFIG_HH
